BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS metrics (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(200) NOT NULL UNIQUE,
    value DOUBLE PRECISION NULL,
    delta BIGINT NULL,
    mtype VARCHAR(200) NOT NULL
);

COMMIT;