version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database_name
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    container_name: app_container
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DATABASE_DSN: postgres://username:password@postgres:5432/database_name
      ADDRESS: http://0.0.0.0:8080

volumes:
  postgres_data: