// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: model/metric_request.proto

package model

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*Metric              `protobuf:"bytes,1,rep,name=metrics" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_model_metric_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_metric_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_model_metric_request_proto_rawDescGZIP(), []int{0}
}

func (x *MetricsRequest) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Type          *string                `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Delta         *int64                 `protobuf:"varint,3,opt,name=delta" json:"delta,omitempty"`
	Value         *float64               `protobuf:"fixed64,4,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_model_metric_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_model_metric_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_model_metric_request_proto_rawDescGZIP(), []int{1}
}

func (x *Metric) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Metric) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *Metric) GetDelta() int64 {
	if x != nil && x.Delta != nil {
		return *x.Delta
	}
	return 0
}

func (x *Metric) GetValue() float64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

var File_model_metric_request_proto protoreflect.FileDescriptor

const file_model_metric_request_proto_rawDesc = "" +
	"\n" +
	"\x1amodel/metric_request.proto\x12\x18metrics.go.grpc.v1.model\"L\n" +
	"\x0eMetricsRequest\x12:\n" +
	"\ametrics\x18\x01 \x03(\v2 .metrics.go.grpc.v1.model.MetricR\ametrics\"X\n" +
	"\x06Metric\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\x03R\x05delta\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05valueB!Z\x1fmetrics/internal/proto/v1/modelb\beditionsp\xe8\a"

var (
	file_model_metric_request_proto_rawDescOnce sync.Once
	file_model_metric_request_proto_rawDescData []byte
)

func file_model_metric_request_proto_rawDescGZIP() []byte {
	file_model_metric_request_proto_rawDescOnce.Do(func() {
		file_model_metric_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_metric_request_proto_rawDesc), len(file_model_metric_request_proto_rawDesc)))
	})
	return file_model_metric_request_proto_rawDescData
}

var file_model_metric_request_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_model_metric_request_proto_goTypes = []any{
	(*MetricsRequest)(nil), // 0: metrics.go.grpc.v1.model.MetricsRequest
	(*Metric)(nil),         // 1: metrics.go.grpc.v1.model.Metric
}
var file_model_metric_request_proto_depIdxs = []int32{
	1, // 0: metrics.go.grpc.v1.model.MetricsRequest.metrics:type_name -> metrics.go.grpc.v1.model.Metric
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_model_metric_request_proto_init() }
func file_model_metric_request_proto_init() {
	if File_model_metric_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_metric_request_proto_rawDesc), len(file_model_metric_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_metric_request_proto_goTypes,
		DependencyIndexes: file_model_metric_request_proto_depIdxs,
		MessageInfos:      file_model_metric_request_proto_msgTypes,
	}.Build()
	File_model_metric_request_proto = out.File
	file_model_metric_request_proto_goTypes = nil
	file_model_metric_request_proto_depIdxs = nil
}
