// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: model/metric_response.proto

package model

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *string                `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_model_metric_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_metric_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_model_metric_response_proto_rawDescGZIP(), []int{0}
}

func (x *MetricsResponse) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

var File_model_metric_response_proto protoreflect.FileDescriptor

const file_model_metric_response_proto_rawDesc = "" +
	"\n" +
	"\x1bmodel/metric_response.proto\x12\x18metrics.go.grpc.v1.model\")\n" +
	"\x0fMetricsResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06statusB!Z\x1fmetrics/internal/proto/v1/modelb\beditionsp\xe8\a"

var (
	file_model_metric_response_proto_rawDescOnce sync.Once
	file_model_metric_response_proto_rawDescData []byte
)

func file_model_metric_response_proto_rawDescGZIP() []byte {
	file_model_metric_response_proto_rawDescOnce.Do(func() {
		file_model_metric_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_metric_response_proto_rawDesc), len(file_model_metric_response_proto_rawDesc)))
	})
	return file_model_metric_response_proto_rawDescData
}

var file_model_metric_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_model_metric_response_proto_goTypes = []any{
	(*MetricsResponse)(nil), // 0: metrics.go.grpc.v1.model.MetricsResponse
}
var file_model_metric_response_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_model_metric_response_proto_init() }
func file_model_metric_response_proto_init() {
	if File_model_metric_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_metric_response_proto_rawDesc), len(file_model_metric_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_metric_response_proto_goTypes,
		DependencyIndexes: file_model_metric_response_proto_depIdxs,
		MessageInfos:      file_model_metric_response_proto_msgTypes,
	}.Build()
	File_model_metric_response_proto = out.File
	file_model_metric_response_proto_goTypes = nil
	file_model_metric_response_proto_depIdxs = nil
}
