// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: service.proto

package v1

import (
	model "metrics/internal/proto/v1/model"
	reflect "reflect"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x12metrics.go.grpc.v1\x1a\x1amodel/metric_request.proto\x1a\x1bmodel/metric_response.proto2m\n" +
	"\aMetrics\x12b\n" +
	"\vSendMetrics\x12(.metrics.go.grpc.v1.model.MetricsRequest\x1a).metrics.go.grpc.v1.model.MetricsResponseB\x1bZ\x19metrics/internal/proto/v1b\beditionsp\xe8\a"

var file_service_proto_goTypes = []any{
	(*model.MetricsRequest)(nil),  // 0: metrics.go.grpc.v1.model.MetricsRequest
	(*model.MetricsResponse)(nil), // 1: metrics.go.grpc.v1.model.MetricsResponse
}
var file_service_proto_depIdxs = []int32{
	0, // 0: metrics.go.grpc.v1.Metrics.SendMetrics:input_type -> metrics.go.grpc.v1.model.MetricsRequest
	1, // 1: metrics.go.grpc.v1.Metrics.SendMetrics:output_type -> metrics.go.grpc.v1.model.MetricsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
